import { makeStyles } from "@material-ui/core";

export const useStyles = makeStyles({
  logo: {
    borderWidth: "0px",
    position: "absolute",
    left: "0px",
    top: "0px",
    width: "260px",
    height: "84px",
  },
  header: {
    borderWidth: "0px",
    position: "absolute",
    left: "0px",
    top: "0px",
    width: "1440px",
    height: "84px",
    background: "inherit",
    backgroundColor: "rgba(75, 40, 109, 1)",
    border: "none",
    borderRadius: "0px",
    boxShadow: "0px",
  },
  heading: {
    borderWidth: "0px",
    position: "absolute",
    left: "308px",
    top: "28px",
    width: "370px",
    height: "30px",
    display: "flex",
    fontFamily: "'Roboto Light 24', 'Roboto Regular', 'Roboto', sans-serif",
    fontWeight: 300,
    fontStyle: "normal",
    fontSize: "24px",
    color: "#FFFFFF",
  },
  text: {
    textDecoration: "underline",
  },
  column_title: {
    color: "#2A2C2E",
    fontSize: "2rem",
    lineHeight: "normal",
    fontWeight: "300",
    fontFamily: "Roboto",
    position: "absolute",
    left: "32px",
    top: "132px",
    width: "111px",
    height: "31px",
  },
  input_field_label1: {
    position: "absolute",
    left: "32px",
    top: "210px",
    width: "111px",
    height: "17px",
    fontSize: "0.875rem",
    textAlign: "left",
  },
  input_field_label2: {
    position: "absolute",
    left: "32px",
    top: "299px",
    display: "flex",
    width: "111px",
    height: "17px",
    fontSize: "0.875rem",
    textAlign: "left",
  },
  input_field_box1: {
    position: "absolute",
    left: "32px",
    top: "240px",
    width: "233px",
    height: "35px",
    display: "flex",
    fontSize: "0.875rem",
    textAlign: "left",
    backgroundColor: "rgba(255, 255, 255, 1)",
    boxSizing: "border-box",
    borderWidth: "1px",
    borderColor: "rgba(177, 177, 177, 1)",
    borderRadius: "4px",
    paddingTop: "10px",
  },
  input_field_box2: {
    position: "absolute",
    left: "32px",
    top: "330px",
    width: "233px",
    height: "35px",
    display: "flex",
    fontSize: "0.875rem",
    textAlign: "left",
    backgroundColor: "rgba(255, 255, 255, 1)",
    boxSizing: "border-box",
    borderWidth: "1px",
    borderColor: "rgba(177, 177, 177, 1)",
    borderRadius: "4px",
    paddingTop: "10px",
  },
  loginBtn: {
    position: "absolute",
    left: "32px",
    top: "404px",
    width: "118px",
    height: "40px",
    display: "flex",
    borderRadius: "4px",
    backgroundColor: "rgba(75, 40, 109, 1)",
    color: "#FFFFFF",
  },
  link1: {
    position: "absolute",
    left: "32px",
    top: "492px",
    // width: "150px",
    height: "22px",
    display: "flex",
    color: "##2A2C2E",
    textDecoration: "underline",
  },
  paperHeading: {
    fontStyle: "normal",
    fontSize: "28px",
    color: "#2A2C2E",
    fontWeight: "300",
    fontFamily: "'Roboto Light', 'Roboto Regular', 'Roboto', sans-serif",
    paddingTop: "14px",
    paddingLeft: "30px",
  },
  paperHeader: {
    fontStyle: "normal",
    fontSize: "14px",
    fontFamily: "'Roboto Medium', 'Roboto Regular', 'Roboto', sans-serif",
    fontWeight: "300",
    color: "#2A2C2E",
    paddingLeft: "30px",
  },
  message: {
    fontStyle: "normal",
    fontSize: "14px",
    fontFamily: "'Roboto Light', 'Roboto Regular', 'Roboto', sans-serif",
    fontWeight: 300,
    color: "#2A2C2E",
    paddingLeft: "30px",
  },
  underline: {
    textDecoration: "underline",
  },
  parentBox: {
    display: "flex",
    flexWrap: "wrap",
    "& > :not(style)": {
      width: "420px",
      height: "326px",
      position: "absolute",
      top: "130px",
      left: "520px",
      shadows: "35px 29px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22)",
    },
  },
  childBox: {
    width: "388px",
    height: "250px",
  },
});
